# Generated by Django 6.0.4 on 2026-04-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Windings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnsPerPhase', models.FloatField(blank=True, null=True)),
                ('phaseCurrent', models.FloatField(default=0.0)),
                ('currentDensity', models.FloatField(default=0.0)),
                ('condCrossSec', models.FloatField(default=0.0)),
                ('conductorSizes', models.CharField(blank=True, default='', max_length=255)),
                ('condInsulation', models.FloatField(blank=True, null=True)),
                ('noInParallel', models.CharField(blank=True, default='', max_length=255)),
                ('windingLength', models.FloatField(default=0.0)),
                ('noOfLayers', models.FloatField(blank=True, null=True)),
                ('turnsPerLayer', models.FloatField(default=0.0)),
                ('terminal', models.FloatField(default=0.0)),
                ('endClearances', models.FloatField(default=0.0)),
                ('eddyStrayLoss', models.FloatField(default=0.0)),
                ('tempGradDegC', models.FloatField(default=0.0)),
                ('ducts', models.IntegerField(blank=True, null=True)),
                ('ductSize', models.IntegerField(blank=True, null=True)),
                ('insulatedWeight', models.FloatField(default=0.0)),
                ('bareWeight', models.FloatField(default=0.0)),
                ('loadLoss', models.FloatField(default=0.0)),
                ('commRawCond', models.FloatField(default=0.0)),
                ('interLayerInsulation', models.FloatField(blank=True, null=True)),
                ('noOfDuctsWidth', models.CharField(blank=True, default='', max_length=255)),
                ('turnsLayers', models.TextField(blank=True, null=True)),
                ('weightBareInsulated', models.CharField(blank=True, default='', max_length=255)),
                ('radialParallelCond', models.IntegerField(blank=True, null=True)),
                ('axialParallelCond', models.IntegerField(blank=True, null=True)),
                ('condBreadth', models.FloatField(blank=True, null=True)),
                ('condHeight', models.FloatField(blank=True, null=True)),
                ('conductorDiameter', models.FloatField(blank=True, null=True)),
                ('isConductorRound', models.BooleanField(blank=True, null=True)),
                ('isEnamel', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
