# Generated by Django 6.0.4 on 2026-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoilDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreDia', models.IntegerField(default=0)),
                ('coreGap', models.FloatField(blank=True, null=True)),
                ('lVID', models.IntegerField(default=0)),
                ('lVRadial', models.IntegerField(default=0)),
                ('lVOD', models.IntegerField(default=0)),
                ('lVHVGap', models.FloatField(blank=True, null=True)),
                ('hVID', models.IntegerField(default=0)),
                ('hVRadial', models.IntegerField(default=0)),
                ('hVOD', models.IntegerField(default=0)),
                ('hVHVGap', models.FloatField(blank=True, null=True)),
                ('activePartSize', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
