# Generated by Django 6.0.4 on 2026-04-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coildimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreType', models.CharField(blank=True, default='0', max_length=255)),
                ('coreDia', models.IntegerField(blank=True, null=True)),
                ('limbHt', models.FloatField(blank=True, null=True)),
                ('cenDist', models.FloatField(default=0.0)),
                ('area', models.FloatField(default=0.0)),
                ('blade', models.CharField(blank=True, default='0', max_length=255)),
                ('wKgGrade', models.FloatField(default=0.0)),
                ('fluxDensity', models.FloatField(default=0.0)),
                ('coreWeight', models.FloatField(default=0.0)),
                ('coreMaterial', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RadialGaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreToLv', models.FloatField(default=0.0)),
                ('LvtoHV', models.FloatField(default=0.0)),
                ('lvToFine', models.FloatField(default=0.0)),
                ('lvToCoarse', models.FloatField(default=0.0)),
                ('lvToOuter', models.FloatField(default=0.0)),
                ('fineToCoarse', models.FloatField(default=0.0)),
                ('fineToOuter', models.FloatField(default=0.0)),
                ('coarseToOuter', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MultiWindings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designId', models.CharField(blank=True, default='', max_length=255)),
                ('windings', models.CharField(blank=True, default='', max_length=255)),
                ('kVA', models.FloatField(default=0.0)),
                ('kValue', models.FloatField(default=0.0)),
                ('lowVoltage', models.FloatField(default=0.0)),
                ('highVoltage', models.FloatField(default=0.0)),
                ('lvCurrentDensity', models.FloatField(default=0.0)),
                ('hvCurrentDensity', models.FloatField(default=0.0)),
                ('fineCurrentDensity', models.FloatField(default=0.0)),
                ('corseCurrentDensity', models.FloatField(default=0.0)),
                ('outerCurrentDensity', models.FloatField(default=0.0)),
                ('lvConductorMaterial', models.CharField(blank=True, default='', max_length=255)),
                ('hvConductorMaterial', models.CharField(blank=True, default='', max_length=255)),
                ('fineConductorMaterial', models.CharField(blank=True, default='', max_length=255)),
                ('corseConductorMaterial', models.CharField(blank=True, default='', max_length=255)),
                ('outerConductorMaterial', models.CharField(blank=True, default='', max_length=255)),
                ('tapStepsPercentage', models.FloatField(blank=True, null=True)),
                ('tapStepPositive', models.IntegerField(blank=True, null=True)),
                ('tapStepNegative', models.IntegerField(blank=True, null=True)),
                ('corseWindings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corseMultiWindings', to='api.windings')),
                ('fineWindings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fineMultiWindings', to='api.windings')),
                ('hvWindings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hvMultiWindings', to='api.windings')),
                ('lvWindings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lvMultiWindings', to='api.windings')),
                ('outerWindings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outerMultiWindings', to='api.windings')),
                ('radialGaps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.radialgaps')),
            ],
        ),
    ]
